### ISSUE TITLE
problems w/ dev version of ggplot2

### ISSUE THREAD

**Issue by jennybc** [dill/emoGG#3] opened 2015-11-27 15:53 UTC
I can't install from GitHub

``` r
> install_github("dill/emoGG")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo dill/emoGG@master
Installing emoGG
Skipping 1 packages not available: Depends:
R
Skipping 1 packages ahead of CRAN: ggplot2
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/vt/4sdxy0rd1b3b65nqssx4sx_h0000gn/T/Rtmpbem45t/devtoolscca466405b5a/dill-emoGG-fe4901c'  \
  --library='/Users/jenny/resources/R/library' --install-tests 

ERROR: dependency ‘Depends’ is not available for package ‘emoGG’
* removing ‘/Users/jenny/resources/R/library/emoGG’
 Show Traceback
 
 Rerun with Debug
 Error: Command failed (1) 
```

If I fix the double "Depends" entries in `DESCRIPTION`, then there's still some sort of fatal trouble ?in the `GeomEmoji()` definition?.

``` r
> check()
Updating emoGG documentation
Loading emoGG
 Show Traceback
 
 Rerun with Debug
 Error in eval(expr, envir, enclos) (from geom_emoji.R#23) : could not find function "eval" 
```

**Comment by dill** [comment] 2015-11-27 15:55
Thanks for the bug report, these didn't show up for me weirdly...

Fixed `Depends` issue in 757a882.

I'll take a look at the latter now...

**Comment by jennybc** [comment] 2015-11-27 16:03
Something to do w/ ggplot2 version maybe?

``` r
> packageVersion("ggplot2")
[1] ‘1.0.1.9003’
```

**Comment by dill** [comment] 2015-11-27 16:09
Aha!

```r
> packageVersion("ggplot2")
[1] '1.0.1'
```

(which seems to be the latest on CRAN?) But, yup updating to the github version I get the same error... I'll dive into that now.

Thanks for the tip! That saved me a lot of time :smile_cat:

**Comment by dill** [comment] 2015-11-27 16:58
Hmm, so, indeed this is to do with changes due for the next `ggplot2` release... The code I've written that works on 1.0.1.9003 doesn't work in 1.0.1.

I'm inclined to track the CRAN releases, as that's what most people will have...

Need to think a bit more deeply about this...

**Comment by dill** [comment] 2015-11-27 17:04
(Also there should now be a `new-ggplot2` branch that does work for 1.0.1.9003, let me know how that goes if you get a chance. I'm off to do other things for a wee bit.)

**Comment by wrathematics** [comment] 2015-11-27 18:08
Based on an email one of our ggplot2-depending packages received, the next release will be in just a few weeks:

> I was planning on submitting the next version of ggplot2 to CRAN on
Friday, but it looks like there are too many problems with existing
packages. The new release target will be Dec 11.

Just FYI.

**Comment by jennybc** [comment] 2015-11-27 19:10
I installed from that branch, which seems to work. But then can't run the README example.

``` r
#install_github("dill/emoGG@new-ggplot2")
library(emoGG)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_emoji(emoji="1f337")
#> Error in FUN(X[[i]], ...) : 
#>   Theme element 'text' has NULL property: margin, debug
```

This failure takes a little while FWIW. (In other news, the example also breaks `reprex()`, which I should also figure out 😧.)

**Comment by jennybc** [comment] 2015-11-27 20:03
I have a suspicion that the transition to the new ggplot2 is going to be pretty painful. The people who teach R and blog about it will switch. But I'm always struck by how old the R, RStudio, and packages are on my students' computers, when they first come to me. Of course I force them to upgrade :) But this is going to hurt.

**Comment by clauswilke** [comment] 2015-11-28 01:00
@jennybc Yes, the new ggplot2 has major changes, and writing packages that support both the current and the new version is going to be a pain. Also, porting existing scripts over can be a lot of work, in particular for scripts that modify the margins properties of axis tick labels. At a minimum, the new ggplot2 should be version 2.0.0. Maybe it even should have been renamed into ggplot3.

**Comment by dill** [comment] 2015-11-30 05:16
@wrathematics & @clauswilke: thanks for this extra info! This was probably a bad time to write this!

@jennybc I can't seem to reproduce this. Running the following:

```{r}
library(devtools)
install_github("hadley/ggplot2")
install_github("dill/emoGG@new-ggplot2")
library(emoGG)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_emoji(emoji="1f337")
```

I get a plot.

My session info is as follows, how does this compare with yours?

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] emoGG_0.0.1        ggplot2_1.0.1.9003 devtools_1.9.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      png_0.1-7        digest_0.6.8     bitops_1.0-6
 [5] grid_3.2.2       R6_2.1.1         plyr_1.8.3       gtable_0.1.2
 [9] scales_0.3.0     httr_1.0.0.9000  curl_0.9.4       labeling_0.3
[13] proto_0.3-10     tools_3.2.2      munsell_0.4.2    RCurl_1.95-4.7
[17] colorspace_1.2-6 memoise_0.2.1    knitr_1.11
```

**Comment by jennybc** [comment] 2015-11-30 19:37
OK I reinstalled both `ggplot2` (`v1.0.1.9003 2015-11-30 Github (hadley/ggplot2@23a748f)`) and `emoGG@new-ggplot2` and it works! My previous `ggplot2` was from early November so perhaps something changed that was favourable for `emoGG`. This plot is quite slow to appear -- do you expect that? Maybe you should put the required `ggplot2` version in `DESCRIPTION` so the installation failure is more informative?

@clauswilke The whole reason I started this was because I wanted to make the plot I **expected** to see when you released `cowplot`. Here you go.

![cowplot](https://cloud.githubusercontent.com/assets/599454/11482243/abcb716a-9756-11e5-8ba9-a722ba102901.png)

**Comment by dill** [comment] 2015-11-30 22:57
@jennybc glad to hear it!

I've added a requirement for these versions to the DESCRIPTION (1d50710 & 0decb31) and updated the README accordingly (0e08f8b & 2555333) for each branch.

Thanks for your collective help figuring this out! :chart_with_upwards_trend: :chart_with_upwards_trend: :chart_with_upwards_trend:

**Closed by dill** 2015-11-30 22:57 UTC
Labels: bug
